# Generated by Django 3.0.5 on 2020-09-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='LONG')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='LAT')),
                ('setcens', models.CharField(max_length=255, verbose_name='SETCENS')),
                ('area', models.CharField(max_length=255, verbose_name='AREAP')),
                ('register', models.CharField(max_length=255, verbose_name='REGISTRO')),
                ('street', models.CharField(max_length=255, verbose_name='LOGRADOURO')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='NÚMERO')),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True, verbose_name='BAIRRO')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='REFERENCIA')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fair', to='district.District', verbose_name='DISTRITO')),
            ],
            options={
                'verbose_name': 'FEIRA',
                'verbose_name_plural': 'FEIRAS',
            },
        ),
    ]
