# Generated by Django 3.0.5 on 2020-09-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'REGIÃO 5',
                'verbose_name_plural': 'REGIÕES 5',
            },
        ),
        migrations.CreateModel(
            name='Zone8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('zone_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_8', to='zone.Zone5')),
            ],
            options={
                'verbose_name': 'REGIÃO 8',
                'verbose_name_plural': 'REGIÕES 8',
            },
        ),
    ]
