# Generated by Django 3.0.5 on 2020-09-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPrefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('zone_8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_prefecture', to='zone.Zone8')),
            ],
            options={
                'verbose_name': 'SUB PREFEITURA',
                'verbose_name_plural': 'SUB PREFEITURAS',
            },
        ),
    ]
